version: '3.8'

services:
  mysql:
    build:
      context: ./infra/db
    container_name: mysql
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./app
    container_name: app
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "4743:4743"

  nginx:
    build:
      context: ./infra/nginx
    container_name: nginx
    networks:
      - site_network
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_volume:

networks:
  db_network:
  site_network:
