version: '3.8'

services:
  mysql:
    build:
      context: ./infra/db
    container_name: mysql_container
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - db_network
    ports:
      - "5655:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./app
    container_name: app_container
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./infra/nginx
    container_name: nginx_container
    networks:
      - site_network
    ports:
      - "5423:824"
    depends_on:
      app:
        condition: service_healthy

volumes:
  db_volume:

networks:
  db_network:
  site_network:
