CREATE DATABASE IF NOT EXISTS test_db;
USE test_db;

CREATE TABLE IF NOT EXISTS test_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

INSERT INTO test_table (name) VALUES ('Sample Data 1') ON DUPLICATE KEY UPDATE id=id;
INSERT INTO test_table (name) VALUES ('Sample Data 2') ON DUPLICATE KEY UPDATE id=id;
